# Generated by Django 4.1.6 on 2023-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В прогрессе'), ('COMPLETED', 'Выполнена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('title', models.CharField(default='null', max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(default='null', max_length=100, verbose_name='Описание')),
                ('detailed_description', models.TextField(default='null', max_length=2500, verbose_name='Подробное описание')),
                ('completion_date', models.DateField(default='', verbose_name='Дата выполнения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
            ],
        ),
    ]
